---
title: "Visualisation homework - group b4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
library(ggplot2)
library(dplyr)
```

The data is taken from http://insideairbnb.com/get-the-data.html
where we are looking at the listings datasets between January 2019 and December 2019 in London.

```{r}
#if order of columns change use [,c("id","availability_30")] instead to select right columns
#using colClasses to only read 2 of the columns in the file that we need
listings1=read.csv("listings.csv",header = TRUE, sep = ",",dec = ".",colClasses=c(NA,rep('NULL',76), NA,rep('NULL',28))) 
listings2=read.csv("listings-2.csv",header = TRUE, sep = ",",dec = ".",colClasses=c(NA,rep('NULL',76), NA,rep('NULL',28)))
listings3=read.csv("listings-3.csv",header = TRUE, sep = ",",dec = ".",colClasses=c(NA,rep('NULL',76), NA,rep('NULL',28)))
listings4=read.csv("listings-4.csv",header = TRUE, sep = ",",dec = ".",colClasses=c(NA,rep('NULL',76), NA,rep('NULL',28)))
listings5=read.csv("listings-5.csv",header = TRUE, sep = ",",dec = ".",colClasses=c(NA,rep('NULL',76), NA,rep('NULL',28)))
listings6=read.csv("listings-6.csv",header = TRUE, sep = ",",dec = ".",colClasses=c(NA,rep('NULL',76), NA,rep('NULL',28)))
listings7=read.csv("listings-7.csv",header = TRUE, sep = ",",dec = ".",colClasses=c(NA,rep('NULL',76), NA,rep('NULL',28)))
listings8=read.csv("listings-8.csv",header = TRUE, sep = ",",dec = ".",colClasses=c(NA,rep('NULL',76), NA,rep('NULL',28)))
listings9=read.csv("listings-9.csv",header = TRUE, sep = ",",dec = ".",colClasses=c(NA,rep('NULL',76), NA,rep('NULL',28)))
listings10=read.csv("listings-10.csv",header = TRUE, sep = ",",dec =".",colClasses=c(NA,rep('NULL',76), NA,rep('NULL',28)))
listings11=read.csv("listings-11.csv",header = TRUE, sep = ",",dec =".",colClasses=c(NA,rep('NULL',76), NA,rep('NULL',28)))
listings12=read.csv("listings-12.csv",header = TRUE, sep = ",",dec = ".")

```

The function to merge the 12 datasets and return the dataset of December 2019 with the sum of 30 days availability throughout the year.

```{r}
merging12<-function(listings1,listings2,listings3,listings4,listings5,listings6,listings7,listings8,listings9,listings10,listings11,listings12){
  temp=merge(listings1,listings2, by="id",suffixes = c(".1",".2"), )
  temp=merge(temp,listings3, by="id",suffixes = c(".2",".3"))
  temp=merge(temp,listings4, by="id",suffixes = c(".3",".4"))
  temp=merge(temp,listings5, by="id",suffixes = c(".4",".5"))
  temp=merge(temp,listings6, by="id",suffixes = c(".5",".6"))
  temp=merge(temp,listings7, by="id",suffixes = c(".6",".7"))
  temp=merge(temp,listings8, by="id",suffixes = c(".7",".8"))
  temp=merge(temp,listings9, by="id",suffixes = c(".8",".9"))
  temp=merge(temp,listings10, by="id",suffixes = c(".9",".10"))
  temp=merge(temp,listings11, by="id",suffixes = c(".10",".11"))
  temp=merge(temp,listings12[,c("id","availability_30")], by="id",suffixes = c(".11",".12"))
  temp$sum_availabiliy_30=temp$availability_30.1 + temp$availability_30.2 + temp$availability_30.3 + temp$availability_30.4 + temp$availability_30.5 + temp$availability_30.6 + temp$availability_30.7 + temp$availability_30.8 + temp$availability_30.9 + temp$availability_30.10 + temp$availability_30.11 + temp$availability_30.12
  result=merge(temp[,c("id","sum_availabiliy_30")],listings12, by="id")
}
```

```{r}
percent_review <- 0.5 # percentage of airbnb guests who leave reviews
avg_stay <- 5.1 # avg length of stay in city

kpi <- function(data){
  data <- data[!is.na(data$first_review) & !is.na(data$review_scores_rating),]
  data$diff_in_days = round(as.numeric(difftime(data$last_scraped, data$first_review, units = "days")))
  data$adj_reviews <- data$number_of_reviews / percent_review
  data$total_stays <- data$adj_reviews * avg_stay
  data$occupancy_rate1 <- data$total_stays / data$diff_in_days # least conservative
  data$occupancy_rate2 <- (data$number_of_reviews * avg_stay) / data$diff_in_days
  data$occupancy_rate3 <- (data$number_of_reviews * data$minimum_nights) / data$diff_in_days # most conservative
  data$occupancy_rate1[data$occupancy_rate1 > 1] = 1
  data$occupancy_rate2[data$occupancy_rate2 > 1] = 1
  data$occupancy_rate3[data$occupancy_rate3 > 1] = 1
  data$kpi1 <- 0.25*(data$review_scores_rating^2/100^2)+0.75*data$occupancy_rate1 # least conservative
  data$kpi2 <- 0.25*(data$review_scores_rating^2/100^2)+0.75*data$occupancy_rate2
  data$kpi3 <- 0.25*(data$review_scores_rating^2/100^2)+0.75*data$occupancy_rate3 # most conservative
  return(data)
}
```

```{r}
#plotting the frequency of occupancy for our 4 possibles KPIs
listings=merging12(listings1,listings2,listings3,listings4,listings5,listings6,listings7,listings8,listings9,listings10,listings11,listings12)
listings=filter(listings, first_review<'2019-01-01', number_of_reviews_ltm>0)
listings$availability_estimation=(365 - listings$sum_availabiliy_30)/365
listings=kpi(listings)
ggplot(listings) + geom_freqpoly(aes(x=kpi1), color="blue")  + geom_freqpoly(aes(x=kpi2), colour="red")  + geom_freqpoly(aes(x=kpi3), color="yellow") + geom_freqpoly(aes(x=availability_estimation))
```


```{r}
filter(listings12, first_review<'2019-01-01', number_of_reviews_ltm>0)
unique(listings12$neighbourhood_cleansed)
```


